server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8

spring:
  application:
    name: ai-hub
  ai:
    openai:
      base-url: https://dashscope.aliyuncs.com/compatible-mode
      api-key: ${ALIYUN_API_KEY}
      chat:
        options:
          model: qwen-plus
          temperature: 0.8
      embedding:
        options:
          model: text-embedding-v3
          dimensions: 1024

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ai_hub?serverTimezone=Asia/Shanghai&useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&tinyInt1isBit=false&allowPublicKeyRetrieval=true&allowMultiQueries=true&useServerPrepStmts=false
    username: root
    password: 123456

logging:
  level:
    org.springframework.ai: debug
    com.adrian.aihub: debug