server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8

spring:
  application:
    name: ai-hub
  ai:
    openai:
      base-url: https://dashscope.aliyuncs.com/compatible-mode
      api-key: ${ALIYUN_API_KEY}
      chat:
        options:
          model: qwen-plus

logging:
  level:
    org.springframework.ai: debug
    com.adrian.aihub: debug